// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCAggiungiCappelloCatalogoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCAggiuntaCatalogoOk() {
    driver.get("http://localhost:8080/dressapp/inserisciProdotto.jsp");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Nike Star");
    driver.findElement(By.name("desc")).click();
    driver.findElement(By.name("desc")).sendKeys("Cappello sportivo unisex");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("19.99");
    driver.findElement(By.name("cat")).click();
    driver.findElement(By.name("cat")).sendKeys("Cappello sportivo");
    driver.findElement(By.name("disp")).click();
    driver.findElement(By.name("disp")).sendKeys("20");
    driver.findElement(By.name("foto")).click();
    driver.findElement(By.name("foto")).sendKeys("star.jpg");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(22) .card-title"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCAggiuntaPrezzoMancante() {
    driver.get("http://localhost:8080/dressapp/inserisciProdotto.jsp");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".form-group:nth-child(1)")).click();
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Nike Star");
    driver.findElement(By.name("desc")).click();
    driver.findElement(By.name("desc")).sendKeys("Cappello sportivo unisex");
    driver.findElement(By.name("cat")).click();
    driver.findElement(By.name("cat")).sendKeys("Cappello sportivo");
    driver.findElement(By.name("disp")).click();
    driver.findElement(By.name("disp")).sendKeys("20");
    driver.findElement(By.name("foto")).click();
    driver.findElement(By.name("foto")).sendKeys("star.jpg");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      WebElement element = driver.findElement(By.name("prezzo"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
  }
  @Test
  public void tCAggiuntaNomeMancante() {
    driver.get("http://localhost:8080/dressapp/inserisciProdotto.jsp");
    driver.manage().window().setSize(new Dimension(974, 523));
    driver.findElement(By.name("desc")).click();
    driver.findElement(By.name("desc")).sendKeys("Cappello sportivo unisex");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("21");
    driver.findElement(By.name("cat")).click();
    driver.findElement(By.name("cat")).sendKeys("Cappello sportivo");
    driver.findElement(By.name("disp")).click();
    driver.findElement(By.name("disp")).sendKeys("20");
    driver.findElement(By.name("foto")).click();
    driver.findElement(By.name("foto")).sendKeys("star.jpg");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("nome"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCAggiuntaDescrizioneMancante() {
    driver.get("http://localhost:8080/dressapp/inserisciProdotto.jsp");
    driver.manage().window().setSize(new Dimension(974, 571));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Nike Star");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("21");
    driver.findElement(By.name("cat")).click();
    driver.findElement(By.name("cat")).sendKeys("Cappello sportivo");
    driver.findElement(By.name("disp")).click();
    driver.findElement(By.name("disp")).sendKeys("21");
    driver.findElement(By.name("foto")).click();
    driver.findElement(By.name("foto")).sendKeys("star.jpg");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      WebElement element = driver.findElement(By.name("desc"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
  }
  @Test
  public void tCAggiuntaCategoriaMancante() {
    driver.get("http://localhost:8080/dressapp/inserisciProdotto.jsp");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Nike Star");
    driver.findElement(By.name("desc")).click();
    driver.findElement(By.name("desc")).sendKeys("Cappello sportivo unisex");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("disp")).click();
    driver.findElement(By.name("disp")).sendKeys("5");
    driver.findElement(By.name("foto")).click();
    driver.findElement(By.name("foto")).sendKeys("star.jpg");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      WebElement element = driver.findElement(By.name("cat"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
    driver.findElement(By.name("prezzo")).sendKeys("19.99");
  }
}
