// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCAggiungiCartaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCCVVObbligatorio() {
    driver.get("http://localhost:8080/dressapp/sceltaPagamento.jsp");
    driver.manage().window().setSize(new Dimension(974, 523));
    driver.findElement(By.name("aggiungiMetodoDiPagamento")).click();
    driver.findElement(By.name("payment-proprietario")).click();
    driver.findElement(By.name("payment-proprietario")).sendKeys("Mario Rossi");
    driver.findElement(By.name("payment-num")).click();
    driver.findElement(By.name("payment-num")).sendKeys("4025678963102456");
    driver.findElement(By.name("payment-scadenza")).click();
    driver.findElement(By.name("payment-scadenza")).sendKeys("02/2025");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("payment-cvv"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCProprietarioObbligatorio() {
    driver.get("http://localhost:8080/dressapp/sceltaPagamento.jsp");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.name("aggiungiMetodoDiPagamento")).click();
    driver.findElement(By.name("payment-num")).click();
    driver.findElement(By.name("payment-num")).sendKeys("4563217896541785");
    driver.findElement(By.name("payment-scadenza")).click();
    driver.findElement(By.name("payment-scadenza")).sendKeys("02/2025");
    driver.findElement(By.name("payment-cvv")).click();
    driver.findElement(By.name("payment-cvv")).sendKeys("201");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("payment-proprietario"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCNumeroCartaObbligatorio() {
    driver.get("http://localhost:8080/dressapp/sceltaPagamento.jsp");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.name("aggiungiMetodoDiPagamento")).click();
    driver.findElement(By.name("payment-proprietario")).click();
    driver.findElement(By.name("payment-proprietario")).sendKeys("Mario Rossi");
    driver.findElement(By.name("payment-scadenza")).click();
    driver.findElement(By.name("payment-scadenza")).sendKeys("02/2027");
    driver.findElement(By.name("payment-cvv")).click();
    driver.findElement(By.name("payment-cvv")).sendKeys("193");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("payment-num"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCAggiungiCartaOk() {
    driver.get("http://localhost:8080/dressapp/sceltaPagamento.jsp");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.name("aggiungiMetodoDiPagamento")).click();
    driver.findElement(By.name("payment-proprietario")).click();
    driver.findElement(By.name("payment-proprietario")).sendKeys("Mario Rossi");
    driver.findElement(By.name("payment-num")).click();
    driver.findElement(By.name("payment-num")).sendKeys("4785201698743258");
    driver.findElement(By.name("payment-scadenza")).click();
    driver.findElement(By.name("payment-scadenza")).sendKeys("02/2025");
    driver.findElement(By.name("payment-cvv")).click();
    driver.findElement(By.name("payment-cvv")).sendKeys("193");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(3) label"));
      assert(elements.size() > 0);
    }
  }
}
