// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCLoginOK() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.name("sigin")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(3)")).sendKeys("mariorossi@gmail.com");
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).sendKeys("mario12");
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).sendKeys(Keys.ENTER);
    assertThat(driver.getTitle(), is("DressApp"));
  }
  @Test
  public void tCLoginPasswordErrata() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(3)")).sendKeys("mariorossi@gmail.com");
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).sendKeys("mario13");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p:nth-child(5)"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCLoginEmailInesistente() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(3)")).sendKeys("mariorossiiii@gmail.com");
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).sendKeys("mario12");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p:nth-child(5)"));
      assert(elements.size() > 0);
    }
  }
}
