// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCRegistrazioneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCRegistrazioneOK() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("signUp")).click();
    driver.findElement(By.name("rec-name")).click();
    driver.findElement(By.name("rec-name")).sendKeys("Osvaldo");
    driver.findElement(By.name("rec-surname")).click();
    driver.findElement(By.name("rec-surname")).sendKeys("Pot");
    driver.findElement(By.name("login-email")).click();
    driver.findElement(By.name("login-email")).sendKeys("osvaldopot@gmail.com");
    driver.findElement(By.name("login-password")).click();
    driver.findElement(By.name("login-password")).sendKeys("osvaldo12");
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(3)")).sendKeys("osvaldopot@gmail.com");
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".sign-in-container input:nth-child(4)")).sendKeys("osvaldo12");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    assertThat(driver.getTitle(), is("DressApp"));
  }
  @Test
  public void tCRegistrazioneEmailInUso() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("signUp")).click();
    driver.findElement(By.name("rec-name")).click();
    driver.findElement(By.name("rec-name")).sendKeys("Mario");
    driver.findElement(By.name("rec-surname")).click();
    driver.findElement(By.name("rec-surname")).sendKeys("Rossi");
    driver.findElement(By.name("login-email")).click();
    driver.findElement(By.name("login-email")).sendKeys("mariorossi@gmail.com");
    driver.findElement(By.name("login-password")).click();
    driver.findElement(By.name("login-password")).sendKeys("mario12");
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    driver.findElement(By.id("signUp")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p:nth-child(6)"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCRegistrazioneEmailNonValida() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("signUp")).click();
    driver.findElement(By.name("rec-name")).sendKeys("Mario");
    driver.findElement(By.name("rec-surname")).click();
    driver.findElement(By.name("rec-surname")).sendKeys("Rossi");
    driver.findElement(By.name("login-email")).click();
    driver.findElement(By.name("login-email")).sendKeys("mariorossigmail.com");
    driver.findElement(By.name("login-password")).click();
    driver.findElement(By.name("login-password")).sendKeys("mario12");
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("button:nth-child(6)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.name("rec-name")).click();
  }
  @Test
  public void tCRegistrazioneEmailMancante() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("signUp")).click();
    driver.findElement(By.name("rec-name")).click();
    driver.findElement(By.name("rec-name")).sendKeys("Mario");
    driver.findElement(By.name("rec-surname")).click();
    driver.findElement(By.name("rec-surname")).sendKeys("Verdi");
    driver.findElement(By.name("login-password")).click();
    driver.findElement(By.name("login-password")).sendKeys("verdi12");
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("login-email"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCRegistrazionePasswordMancante() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("signUp")).click();
    driver.findElement(By.name("rec-name")).click();
    driver.findElement(By.name("rec-name")).sendKeys("Mario");
    driver.findElement(By.name("rec-surname")).click();
    driver.findElement(By.name("rec-surname")).sendKeys("Verdi");
    driver.findElement(By.name("login-email")).click();
    driver.findElement(By.name("login-email")).sendKeys("marioverdi@gmail.com");
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("login-password"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCRegistrazioneNomeMancante() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("signUp")).click();
    driver.findElement(By.name("rec-surname")).click();
    driver.findElement(By.name("rec-surname")).sendKeys("blu");
    driver.findElement(By.name("login-email")).click();
    driver.findElement(By.name("login-email")).sendKeys("blu@gmail.com");
    driver.findElement(By.name("login-password")).click();
    driver.findElement(By.name("login-password")).sendKeys("blu12");
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("rec-name"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCRegistrazioneCognomeMancante() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("signUp")).click();
    driver.findElement(By.name("rec-name")).click();
    driver.findElement(By.name("rec-name")).sendKeys("Giuseppe");
    driver.findElement(By.name("login-email")).click();
    driver.findElement(By.name("login-email")).sendKeys("giuseppe@gmail.com");
    driver.findElement(By.name("login-password")).click();
    driver.findElement(By.name("login-password")).sendKeys("giuseppe12");
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("rec-surname"));
      assert(elements.size() > 0);
    }
  }
}
