// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCRicercaCappelloTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCRicercaNomeMancante() {
    driver.get("http://localhost:8080/dressapp/search-bar?search=");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.cssSelector(".fa")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(1) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(2) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(3) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(4) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(5) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(6) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(7) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(8) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(9) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(10) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(11) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(12) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(13) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(15) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(16) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(17) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(18) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(19) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(20) .card-img-top"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-md-3:nth-child(14) .card-img-top"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCRicercaAvvenutaConSuccesso() {
    driver.get("http://localhost:8080/dressapp/show-products");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("search")).sendKeys("nike u");
    driver.findElement(By.cssSelector(".fa")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".card-title"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCRicercaFallita() {
    driver.get("http://localhost:8080/dressapp/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("search")).sendKeys("New Balance");
    driver.findElement(By.cssSelector(".fa")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("h3"));
      assert(elements.size() > 0);
    }
  }
}
